manfredsteyer/angular-oauth2-oidc

src/oauth-service.ts

Implements the suggestion in issue #46

Added postLogoutRedirectUri to OAuthService

---

src/oauth-service.ts

Added login hint for prefill the username/email field in the login, according to the specification.
It was tested with an AspNetCore Identity Server 4 using implicit flow.

Added login hint.

---

src/oauth-service.ts

handle error on login

---

angular-oauth2-oidc/src/auth.config.ts

docs: typo

---

README.MD

Update README.MD - Fix typo for Keyloak Redhat

---

README.MD

Corrected some typos and add Okta Developer blog tutorials that use this library

Add tutorials from Okta Developer Blog

---

angular-oauth2-oidc/package.json
package.json

Just for the sake of completeness :-)

Updates repository and bug url in package.json

---

README.md

Just fixing the bottom link to the documentation

Fixing broken documentation link

---

README.md

Clarify imports in README example
Fixes #365

Clarify imports in README example

---

docs-src/events.md

Improve documentation for events

---

README.md
docs-src/configure-custom-oauthstorage.md
docs-src/summary.json
docs/additional-documentation/configure-custom-oauthstorage.html

 Add documentation about configuring custom OAuthStorage

---

projects/lib/src/oauth-service.ts

Error messages were missing the `s`.

Fixed HTTPS error messages in service

---

projects/lib/src/oauth-service.ts

This minor improvement will make this library more usable.

Add more types in OAuthService

---

package-lock.json
projects/lib/src/oauth-service.ts

replace document with injectionToken

---

README.md

`.../implicit-flow.html` should be `.../using-implicit-flow.html`

Fix docs URL for implicit flow

---

docs-src/code-flow.md

Hello,
Minor PR to correct a few spelling mistakes in the code-flow.md documentation
Thanks

Correct some spelling mistates in code-flow.md

---

projects/lib/src/oauth-service.ts
projects/lib/src/types.ts

fix: Disable nonce validation for id token for e2e tests

---

projects/lib/src/interceptors/default-oauth.interceptor.ts

When reading the code I stumbled upon this unused variable.

Remove unused variable

---

projects/lib/src/oauth-service.ts

#854 Adds basic support for JWT (JWS/JWE) responses on userinfo endpoint. The support added here is very basic and just intended to prevent the client from breaking.

feat: support JWT response on userinfo endpoint

---

projects/lib/src/oauth-service.ts

Fix issue with replacement of code and state in URL

---

docs-src/authsvr-auth0.md
docs/classes/AuthConfig.html
projects/lib/src/auth.config.ts

Just solve a minor typo in ``authsvr-auth0.md`` file

Fix minor typos in "authsvr-auth0.md"

---

projects/lib/src/oauth-service.ts

address issues with firefox and Angular router
Closes #970

fix: clear location.hash only if it is present

---

projects/lib/src/oauth-service.ts

fix: in code flow pass options to error handler

---

projects/lib/src/auth.config.ts
projects/lib/src/oauth-service.ts

Fixes #895 postLogoutRedirectUri should not default to redirectUri

feat(logout): postLogoutRedirectUri should not default to redirectUri

---

docs-src/token-refresh.md

Line 5: "an refresh token" should be "a refresh token"

Fixed typo

---

projects/lib/src/oauth-service.ts

add max value on calcTimeout function

---

package-lock.json
package.json
projects/angular-oauth2-oidc-jwks/package.json

Fix for https://github.com/manfredsteyer/angular-oauth2-oidc/issues/1391
Updating jsrsasign version to `11.0.0`

chore: Update jsrsasign due to CVE-2024-21484 Marvin attack of RSA and RSAOAEP decryption

---

projects/lib/src/oauth-service.ts

Just some typos I stumbled over when reading through the service.

Fix typos in comments
