src/oauth-service.ts
WSO2 Identity Server returns aud as an array which breaks the guard at line 341 in oauth-service.ts. This pull request modifies the guard to properly handle this situation.
=> Fix issue when claim.aud is an array

src/oauth-service.ts
This fixes a bug where the state is url encoded when sent but was not url decoded
on receipt. Therefore ";" gets encoded to "%3B" and breaks nonce checking logic.
=> Fix state bug

src/oauth-service.ts
#52
Parameterize `responseType` and maintain `token` as the default value. This allows it to be set to something other than `token` or `token_id`.
=> Parameterize Response Type so It Can Be Overridden

README.MD
Edited module name from import in Home-Component Example. It had the old module name 'angular2-oauth2/oauth-service' to import the OAuthService.
=> Update import module name in README.MD

src/oauth-service.ts
This fixes issue #23 in the library whereby if the returning state is url encoded, the nonce cannot be split from the state string and verified.
The changes decode the state and check if the decoded state is the same as the provided state. If they are different, the decoded state is used.
=> Fixes #23 - Check for URI encoding before split state

package.json, src/oauth-service.ts
I have added the option to pass customised headers to the fetchTokenUsingPasswordFlow. I am calling a security service that requires basic authentication before I can POST the user credentials to obtain a token.
=> add optional headers for username password flow

angular-oauth2-oidc/src/oauth-service.ts
GET-Parameter `&login_hint` is only set if it has a value.
The server I am using does not play nicely if there is a `&login_hint=` at the end of the Query-String.
=> Make parameter login_hint optional

angular-oauth2-oidc/src/index.ts
Although HttpModule is going to be deprecated in v5, we should have it in imports until you switch to use HttpClientModule.
=> fix: missing HttpModule dependency

angular-oauth2-oidc/src/events.ts, angular-oauth2-oidc/src/oauth-service.ts
This PR adds the 'logout' event to notify subscribers that the `logout()` function was called.
There is currently a 'session_terminated' event but that is not always emitted when `logout()` is called. (e.g. when `this.logoutUrl` is null or `noRedirectToLogoutUrl` is false).
=> Add 'logout' event

angular-oauth2-oidc/src/oauth-service.ts
When the logout URL has a parameter, the URL was constructed incorrectly, first parameter would be added with a "?" instead of a "&", which resulted in an URL with two "?" which is invalid.
Corrected by checking if the URL already contains a "?", and if it does, add the first parameter with a "&" instead of a "?".
Fixes #134
=> Fixed the issue when logout URL has a parameter

README.MD
mixed usage of oauth and oAuth when accesing members in Readme lead to non functional code
=> Updated Readme: fixed mixed usage of oauth and oAuth

sample/src/app/auth-no-discovery.config.ts
Before, `ng serve` in sample/ would fail with
ERROR in sample/src/app/auth-no-discovery.config.ts (24,3): Type '{ 'clientId': string; 'redirectUri': string; 'postLogoutRedirectUri': string; 'loginUrl': string;...' is not assignable to type 'AuthConfig'.
Object literal may only specify known properties, and ''siletRefreshTimeout'' does not exist in type 'AuthConfig'
=> sample: remove erroneous key 'siletRefreshTimeout'

angular-oauth2-oidc/src/oauth-service.ts
leads to two effects
If a CanActivate or CanLoad guard is initializing the implicit flow, this may occur before the discover document is loaded and the loginUrl is initialized. The effect is, that an login url just consisting of the parameter part is constructed and thus redirect to the app component. The app component on her site again starts the loading of the discovery document and perhaps (loadDiscoveryDocumentAndLogin) another implicit flow.
This pull request changes the initImplicitFlow in a manner, that it checks wether the loginUrl is not an empty string or else subscribes to the discovery_document_loaded event to build up the login url to redirect to.
In the case of an implicit flow initialized by an CanActivate or CanLoad guard the developer potentially hands over the path to …
=> Implicit flow

angular-oauth2-oidc/src/oauth-service.ts
This is about the loadDiscoveryDocumentAndTryLogin and the loadDiscoveryDocumentAndLogin methods, that both using the tryLogin method internally. The tryLogin Method has the optional parameter options of type loginOptions. This pull request extends the former methods with an options parameter.
=> Use of LoginOptions

angular-oauth2-oidc/src/oauth-service.ts
`URLSearchParams` is undefined in IE/Edge. We can import it from `Http` module to fix its reference error. By the way, we moved to new `HttpClient` module that included `HttpParams`. 
This PR changes `URLSearchParams` to `HttpParams` that can fix IE/Edge problem and goes for HttpClient way.
=> Update to HttpParams for new HttpClient

angular-oauth2-oidc/src/encoder.ts, angular-oauth2-oidc/src/oauth-service.ts
fix https://github.com/manfredsteyer/angular-oauth2-oidc/issues/268
=> use custom encoder to allow + in password 

angular-oauth2-oidc/src/auth.config.ts
this allows people who produced configuration files as large objects(why I had to extend auth config with this). To add it as part of the configuration in a type safe way.
=> Allow for partial config

projects/lib/src/interceptors/default-oauth.interceptor.ts, projects/lib/src/oauth-module.config.ts, projects/lib/src/oauth-service.ts
After getting 4.0.0 i faced 2 issues:
1) Getting error on ```grantedScopes.split('+')```. thing is that IdentityServer4 does not send this information at least in my case (as far as i understand it checks allowed scoped agains issued token on request) so it should be optional.
2) Allowed urls where required with check ```startsWith```. So in our case we are calling api without domain e.g. /api on DEV, QA, PROD environments but on localhost we call it with host. This is because on other environments proxy redirect is grabing requests to avoid OPTIONS request since API and web are separated. On other hand on localhost we do not have any proxy so we have to call full url like http://api..../.... So we are ending up mixed situations. We could change this check with indexOf but this is not …
=> Fixed bug with required grant and made allowedUrls optional

projects/lib/package.json
currently npm doesn't link back to the repo/github
=> add missing repository field

projects/lib/src/oauth-service.ts
Check user requestType paramater before apply default responseType. So the user can define the behavior.
Closes: #385
See: https://github.com/manfredsteyer/angular-oauth2-oidc/issues/385
=> Use responseType parameter

projects/lib/src/oauth-service.ts
Change 'Authentication' to 'Authorization'
Fixes #368
=> Change 'Authentication' to 'Authorization'

.gitignore, package.json, projects/lib/src/oauth-service.ts
LoadDiscoveryDocumentAndLogin returned Promise<boolean>, which we liked, so I made the other login functions do the same.  This Improves the flow of the login code for us because you don't need to rely on a callback to determine if the login was successful
=> Make all of the login functions return Promise<boolean>

projects/lib/src/oauth-service.ts
Following issue #440 here is my suggestion to run session checks outside of Angular so that view refresh is not triggered with every interval.
=> Session check changed to run outside of Angular zone

projects/lib/src/oauth-service.ts
=> Resolves #439

LICENSE
In #30 the maintainer @manfredsteyer mentions adding an MIT license, but in 5b8cbbe it was accidentally removed. In #385 it was mentioned that the license should be added back. So that's what we do here!
Fixes #370
See also #385
See also #30
=> Add LICENSE back to repository

projects/lib/src/oauth-service.ts
ID token often has significantly shorter expiry time compared to access token. This PR adds a non-destructive option to `setupAutomaticSilentRefresh()` which allows to only watch for certain kind of token expiry. This also solves issue #432.
=> Added option to set up silent refresh only for certain type of token.

projects/lib/src/oauth-service.ts
This PR adds a new method `initImplicitFlowInPopup` which opens a new `Window` to the `silentRefreshRedirectUri` with the `display=popup` query param.
It performs the implicit flow inside the popup, inspired on how silent renewal is being done.
=> Proposal: Add implicit flow through popup

projects/lib/src/auth.config.ts, projects/lib/src/oauth-service.ts
We needed wider time window when validating token expiration in some test scenarios. We added optional config parameter `clockSkewInSec` which overrides default time window of 10mins.
=> Added clock skew parameter

README.md
Hello,
Firstly, thank you very much for this awesome library. At my company, we build a lot of Angular applications in an Openid Connect environment and this dependency is a must. Having helped some teams implementing it, when coming to the interceptor part, I discovered that most people use a classic http interceptor and use the first snippet of code for sending the access token.
This is sad because the feature you implemented in the 3.1 version is really great and this white listing mechanism is very convenient and improve the security. I think it deservers to be the only displayed implementation in the Readme, which should focus on a basic setup, and let the documentation display alternative ways, which it already does very well. Also, the 3.1 version has been out for a year and half …
=> Only present the sendAccessToken interceptor mechanism in the Readme

projects/lib/src/oauth-service.ts
Follow up to https://github.com/manfredsteyer/angular-oauth2-oidc/pull/538
=> optionally use crypto to generate nonce

projects/lib/src/oauth-service.ts
Allow aborting the current implicit flow. This allows restarting an
implicit flow within SPAs.
=> feature: Abort current implicit flow

projects/lib/src/oauth-service.ts
The `noPrompt` parameter was already present in the `silentRefresh` method but it wasn't in the `setupAutomaticSilentRefresh` method
=> Add noPrompt parameter to setupAutomaticSilentRefresh method

projects/lib/src/oauth-service.ts
You can not provide `localStorage` directly via `useValue`, you need to have a factory for that.
=> Corrects how localStorage could be used

docs-src/discovery-document-validation.md, docs-src/implicit-flow-config-discovery.md, docs-src/summary.json
As a follow-up to the [closed] issue https://github.com/manfredsteyer/angular-oauth2-oidc/issues/419
Requesting to update the README with instructions for configuring ID Providers that do not have the issuer url as the base for other url's at the discovery endpoint. For these ID Providers, the `strictDiscoveryDocumentValidation` parameter must be set to `false` in order for the library to function.
The discovery document validation is not part of OIDC specification. OIDC Specification states that the Issuer property can optionally contain path components in the uri scheme (https://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery)
=> update README re: discovery doc validation disabling

projects/lib/src/oauth-service.ts
A proposed fix to solve what is described in #467
If we don't do this, we could wait too long after a refresh of the app. We still use the storedAt variable to determine when we are in the last chunk (gray zone) of time (using the timeoutFactor), and make negative Delta's 0 (zero). co-creds go to @RubenVermeulen 
! We have not yet had the chance to test this fix.
=> Calculate the timeout using now as a reference

projects/lib/src/oauth-service.ts
When using HMR the service may get recreated, this implements `OnDestroy` and clears tokens timers
=> Cleanup timers when OAuthService is destroyed

projects/lib/src/oauth-service.ts
This addresses https://github.com/manfredsteyer/angular-oauth2-oidc/issues/661 based on Ping Federates implementation of at_hash
"Based on spec the at_hash check is only true for implicit code flow on Ping Federate
https://www.pingidentity.com/developer/en/resources/openid-connect-developers-guide.html"
=> Fix for issue 661

projects/lib/src/oauth-service.ts
If userinfo_endpoint not exists in discovery document, update it from auth config field.
=> Set userinfoEndpoint if userinfo_endpoint not exists

projects/lib/src/oauth-service.ts
Fix for https://github.com/manfredsteyer/angular-oauth2-oidc/issues/277
=> Fix destroying route via silentRefresh when using hash strategy (Issue 277)

projects/lib/src/oauth-service.ts
I remove the silent renew and sessioncheck iframes with corresponding message event listeners plus the session check timer
I think this will fix #665, but I might have missed some resources
=> Clean up more resources in ngOnDestroy

projects/lib/src/oauth-service.ts
Trying to run code+PKCE flow from cordova via in app browser. Implicit flow respecting provided openUri method but code flow not.
=> Fixed not using config.openUri in code flow

projects/lib/src/events.ts, projects/lib/src/oauth-service.ts
This PR adds code to handle following popup related errors.
1. Popup closed by end user before authentication is done, i.e., before success redirect url is reached, and tokens have arrived to client
2. Popup blocked by browser. This is required because any js based attempt to open popup window will be generally blocked by browser. So for such cases end user should be informed accordingly.
=> Added popup related error handling for implicit grant

projects/lib/src/oauth-service.ts, projects/sample/src/app/app.routes.ts, projects/sample/src/app/auth-code-flow.config.ts, projects/sample/src/app/auth.config.ts, projects/sample/src/app/home/home.component.html, projects/sample/src/app/home/home.component.ts
Resolves #594 
Renamed and moved `parseQueryString` on `OAuthService` to  `getCodePartsFromUrl` and changed it so that if `window.location.search` is empty, it will try to get the parameters from the hash part (re-using `getHashFragmentParams()` on the urlHelper, which is also already used in `tryLoginImplicitFlow`).
Also added a checkbox to the sample page to toggle the sample app between path and hash location strategy in order to test this.
Should work also with implicit flow, but the redirect uri with the hash route is not yet recognized by the IdentityServer3 instance on `steyer-identity-server.azurewebsites.net`, so that needs to be configured to also support the redirect uri with the hash for the sample test case for implicit flow.
=> Support hash location strategy with code flow

projects/lib/src/oauth-service.ts
Handling messages from other iframes makes no sense and leads to memory leaks. Fixes https://github.com/manfredsteyer/angular-oauth2-oidc/issues/616
=> During session check, ignore messages with irrelevant origin

docs/classes/AuthConfig.html, docs/injectables/OAuthService.html, projects/lib/src/auth.config.ts
Thank you for creating this very easy to use and usefull Angular oidc lib! A very small PR for a small issue, allowing the `clockSkewInSec` from the `AuthConfig`-class to be set to any `number` instead of the literal `600`.
=> Allow clockSkewInSec to be different from 600

projects/lib/src/oauth-service.ts
Instead of only setting a token expiration timer for the shortest
living token type, set timers for both token types as long as they are
valid.
This solves the remaining issue mentioned by @davdev82 in #432 and #462: If the id token has a shorter lifespan than the access token andyou configure setupAutomaticSilentRefresh to only listen to access token expiration, the token will never be refreshed. Because the filtering of the token expiration of token types now happens in setupAutomaticSilentRefresh(), setupExpirationTimers() should set timers for both token types.
With this commit, the `events` Observable now emits when either the id token or the access token expires (instead of only the one with the shortest lifetime), which is also more complete behavior.
=> Always set expiration timers for valid token types

projects/lib/src/oauth-service.ts
When generating noonce, SSR is failing due to self not being defined.
Proposing this change to check this and let it fall back when running on the server side.
=> Validate self when calling crypto provider

projects/lib/src/interceptors/default-oauth.interceptor.ts
Before this change user needed to define both `allowedUrls` and `customUrlValidation` to make `customUrlValidation` work, otherwise it was never executed.
=> Removed duplicated condition for allowedUrls during interceptor logic and make it optional

docs-src/implicit-flow.md, projects/sample/src/app/auth-code-flow.config.ts, projects/sample/src/app/home/home.component.html, projects/sample/src/app/home/home.component.ts, projects/sample/src/silent-refresh.html
Add in the sample app login with popup examples
This should cover both normal popup and normal login flow + implicit and
code flows
=> Update sample app and silent-refresh.html script

projects/lib/src/oauth-service.ts
=> Add optional state parameter for logout

projects/lib/src/oauth-service.ts
In tryLoginCodeFlow options.customHashFragment can be passed to override window.location.search in case of a loginFlow running in popup. a querySource const is setup that is assing to that option if set and default to window.location.search but that const was not used to get parts (window.location.search was used instead). This request fix this behavior and correctly use the querySource const.
=> fix customHashFragment usage in tryLoginCodeFlow

projects/lib/src/auth.config.ts, projects/lib/src/oauth-service.ts
* Config now supports customTokenParameters for IDP's that send extra properties in their TokenRepsonse
* OAuthService now has an API to retrieve those customParameters
* On logout, remove customParameters from storage
Addresses feature request : https://github.com/manfredsteyer/angular-oauth2-oidc/issues/737
=> Support predefined custom parameters extraction from the TokenResponse

projects/lib/src/oauth-service.ts
window.location.search is "" when using the iframe.
The querySource seems to have the correct value
A fix for #600
=> Fixed not working silent refresh when using 'code'

docs-src/silent-refresh.md
The link for the token refresh example has changed and this link was pointing the outdated one.
=> Update a 404 link

README.md
=> Update README with 9.1.0 breaking change

projects/lib/src/oauth-service.ts
Hi everyone,
this PR solves issue #773. Since this PR is a bit of a workaround, I wanted to share a few details on what I found on the issue, in case you want to search for a better solution. So please feel free to ignore the following ;-)
With View Engine and [strictMetadataEmit](https://angular.io/guide/angular-compiler-options#strictmetadataemit) enabled, using ambient types did throw a build-time error ([Could not resolve type](https://angular.io/guide/aot-metadata-errors#could-not-resolve-type)), even when correctly injecting a provider with `@Inject()`. Also see issue [https://github.com/angular/angular/issues/20351](https://github.com/angular/angular/issues/20351). This seems to have been fixed with Ivy: [https://github.com/angular/angular/issues/23395#issuecomment-600355368](https: …
=> Fix error with ambient type when running Universal

projects/lib/src/oauth-service.ts
Every response_Type including 'code' needs a code_challenge. https://github.com/manfredsteyer/angular-oauth2-oidc/issues/804
=> response_types including 'code' gets a code_challenge

projects/lib/src/oauth-service.ts
If the response type 'id_token' is in the implicit flow, no at_hash value is provided in the id_token. https://github.com/manfredsteyer/angular-oauth2-oidc/issues/789
=> 'disableAtHashCheck' by default if responseType is 'id_token'

projects/lib/src/oauth-service.ts
Replaced document by this.document this uses the injected service instead of the native object.
=> Replaced document by this.document #773

docs/additional-documentation/silent-refresh.html
Change the link path to the ".html" page instead of ".md". In the path "https://manfredsteyer.github.io/angular-oauth2-oidc/docs/additional-documentation/silent-refresh.html" the "Token Refresh" link is not pointing to the html page.
=> Changes the link path " Token Refresh"

projects/lib/src/oauth-service.ts
Please add custom grant type support (I'm not very familiar with Angular, but we highly need this functionality)
=> Custom grant type added

docs-src/silent-refresh.md, projects/lib/src/oauth-service.ts, projects/sample/src/silent-refresh.html
Currently, `initLoginFlowInPopup` method is expecting to receive a message from the popup via `postMesage` by subscribing to it via:
```
window.addEventListener('message', listener);
```
Unfortunately this doesn't always work: when the auth provider is on a different domain and the auth process includes redirects within the popup to even more upstream authentication authorities on a third domain and the flow eventually comes back to the original application domain, the popup no longer "remembers" its `window.opener`. [AFAIU this is done for security reasons.](https://stackoverflow.com/a/7120602). This means that the popup has no one to `postMessage` to, and the parent application is left there waiting forever.
This MR suggests adding a storage event fallback. The parent application …
=> Listen for storage to receive auth hash from popup

package.json, projects/lib/src/oauth-service.ts
=> Add loginHint to codeFlow

projects/lib/src/oauth-service.ts
Adds missing `encodeURIComponent` when replacing placeholders, fixes #948.
=> Add missing encodeURIComponent when replacing placeholders

projects/lib/src/interceptors/default-oauth.interceptor.ts
Using double not operator (`!!`) instead of conditional expression to filter truthy tokens during http interception.
=> Simplify filtering of truthy tokens

package-lock.json, projects/lib/src/oauth-service.ts, projects/sample/src/app/home/home.component.html, projects/sample/src/app/home/home.component.ts
As of now, when stopping the automatic refresh in code flow and starting it again, calls to the token endpoint will start multiplying. Depending on the timing some will get rejected based on already used refresh token. 
Managed to track it down to the subscription from events in setupAutomaticSilentRefresh not being unsubscribed together with the other timers.
=> fix: multiplying calls to token endpoint in code flow

projects/lib/src/oauth-service.ts
Checking listenTo after debounceTime can sometimes wrong because the debounceTime can return either access_token or id_token.
It is quite hard to reproduce this bug, depends on the sequence of events of the expired access_token and id_token. Sometimes it is in a different order and causes checking the listenTo after `debounceTime` wrong.
Ref: https://rxjs-dev.firebaseapp.com/api/operators/debounceTime
=> fix: listenTo param of `setupAutomaticSilentRefresh`

projects/lib/src/oauth-service.ts
Skip validateNonce() check for tryLoginCodeFlow() in case if options.disableOAuth2StateCheck is true
=> disableOAuth2StateCheck before calling validateNonce() in code flow

projects/lib/src/oauth-service.ts
In case revocation_endpoint is not present in the openid configuration, the user provided revocationEndpoint should be used by default.
Otherwise the openid configuration will overwrite it to undefined regardlessly, and the user provided revocationEndpoint is not used at all.
=> Use configured revocationEndpoint by default

package.json, projects/angular-oauth2-oidc-jwks/package.json
This PR should close
https://github.com/manfredsteyer/angular-oauth2-oidc/issues/917
=> jwks adding license

projects/angular-oauth2-oidc-jwks/package.json
Solves security vulnerability in angular-oauth2-oidc-jwks.
Closes #1061.
=> fix(jwks): update jsrsasign dependency to 10.2.0

docs-src/silent-refresh.md, docs-src/summary.json
This PR targets issue #1129.
I hope this PR is fine (was not totally sure about the contribution guidelines).
It's my first PR to OS so please be patient with me 😛
=> docs: fix broken link in silent-refresh documentation pointing to token-refresh

projects/lib/src/auth.config.ts, projects/lib/src/oauth-service.ts
I added a new option `preserveRequestedRoute` which is `false` by default.
If set to true and when using the code flow, the requested route and query params are stored to storage and after successful token retrieval used to redirect to. This feature enables deep linking.
Fixes #592
=> Preserve requested route for code flow

projects/lib/src/oauth-service.ts
Issue:
Running the library as a third-party (eg. inside an iFrame) when third-party cookies are disabled (as is starting to be default setting in browsers) or cookies disabled, also disables access to localStorage. This can be worked around by providing a custom storage in configuration, but it still breaks because the check for setting saveNoncesInLocalStorage breaks at `typeof window['localStorage'] !== 'undefined'` due to access issues.
Fix:
Do the check inside try/catch.
=> Add check for localStorage writeability

projects/lib/src/oauth-service.ts
fix for https://github.com/manfredsteyer/angular-oauth2-oidc/issues/1210
=> disableNonceCheck always leads to an error #1210

projects/lib/src/oauth-service.ts
See #1451 
Getting a token with code flow throws the wrong error type, making distinction between getting a token and refreshing a token impossible
=> throw token_error instead of token_refresh_error
